update the default .mega.conf; only check isMegaFile when git-mega installed

diff --git a/bin/git b/bin/git
--- a/bin/git
+++ b/bin/git
@@ -1,4 +1,6 @@
 #!/bin/bash
+
+
 real_git=$(which -a git | sed -n '2p')
 if [[ -z "$real_git" ]]; then
   echo "git: No such file or directory"
@@ -10,23 +12,25 @@ if [[ -z "$git_root" ]]; then
   exec $real_git "$@"  # real git will terminte the process and exit
 fi
 
-if [[ "$1" == "add" ]] || [[ "$1" == "commit" ]]; then
-  if [[ "$1" == "add" ]]; then
-    file_list=$(git ls-files --others --modified --exclude-standard $@)
-  else
-    file_list=$(git diff --cached --name-only)
-  fi
-
-  for file in $file_list; do
-    if [[ -f "$file" ]]; then # skip removed files
-      if $(isMegaFile  $git_root/.mega.conf  $file); then
-        size=$(stat -c %s "$file")
-        echo "found mega file: $file ($size bytes)"
-        echo "run 'git mega deposit <file>|<path>' first"
-        exit 1
-      fi
+if [[ -s "$git_root"/.mega.conf  ]]; then # if git-mega installed
+  if [[ "$1" == "add" ]] || [[ "$1" == "commit" ]]; then
+    if [[ "$1" == "add" ]]; then
+      file_list=$(git ls-files --others --modified --exclude-standard $@)
+    else
+      file_list=$(git diff --cached --name-only)
     fi
-  done
+
+    for file in $file_list; do
+      if [[ -f "$file" ]]; then # igore removed files
+	if $(isMegaFile  $git_root/.mega.conf  $file); then
+	  size=$(stat -c %s "$file")
+	  echo "\"git $1\" failed. Found mega file: $file ($size bytes)"
+	  echo "run 'git mega deposit <file>|<path>' first"
+	  exit 1
+	fi
+      fi
+    done
+  fi
 fi
 
 # Pass to real git
